# Generated by Django 4.1.3 on 2022-12-08 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.child'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_made',
            field=models.IntegerField(default=False),
        ),
    ]
