# Generated by Django 4.1.3 on 2022-12-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_booking_child_alter_booking_payment_made"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="payment_made",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
